# Generated by Django 2.2.7 on 2019-12-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(upload_to='media')),
                ('quantidade_pagina', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Genero', verbose_name='livros')),
            ],
        ),
    ]
