# Generated by Django 2.2.7 on 2019-12-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=11)),
                ('diretor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenacao_letra', models.CharField(max_length=1)),
                ('quantidade', models.IntegerField()),
                ('posicao', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.TextField()),
                ('numero', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Genero', verbose_name='estante')),
                ('prateleira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Prateleira', verbose_name='livros')),
            ],
        ),
    ]
