# Generated by Django 2.2.7 on 2019-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0002_auto_20191217_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='ano_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_lancamento',
            field=models.DateField(null=True),
        ),
    ]
