# Generated by Django 2.2.7 on 2019-12-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0003_auto_20191217_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.RenameField(
            model_name='prateleira',
            old_name='quantidade',
            new_name='quantidade_atual',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prateleira',
            name='quantidade_suportada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estante',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Genero', verbose_name='estantes_genero'),
        ),
        migrations.AlterField(
            model_name='estante',
            name='prateleira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Prateleira', verbose_name='estantes_prateleira'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_lancamento',
            field=models.DateField(default='2010-12-12'),
            preserve_default=False,
        ),
    ]
