# Generated by Django 2.2.7 on 2019-12-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0004_auto_20191226_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estante',
            name='bloco',
        ),
    ]
