# Generated by Django 2.2.7 on 2019-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0005_remove_estante_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prateleira',
            name='ordenacao_letra',
            field=models.CharField(max_length=3),
        ),
    ]
