# Generated by Django 3.0.1 on 2019-12-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca_api', '0006_auto_20191226_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Livro', verbose_name='multas_relacionadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Usuario', verbose_name='multas')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Livro', verbose_name='multas_relacionadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Usuario', verbose_name='multas')),
            ],
        ),
    ]
