# Generated by Django 3.0.1 on 2019-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0007_emprestimo_multa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateField(default='2010-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolver',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='aberta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='paga',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
