# Generated by Django 3.0.1 on 2019-12-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0009_remove_multa_aberta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multa',
            old_name='paga',
            new_name='pagar',
        ),
    ]
