# Generated by Django 3.0.1 on 2019-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0011_auto_20191226_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateField(null=True),
        ),
    ]
