# Generated by Django 3.0.1 on 2019-12-27 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca_api', '0012_auto_20191227_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estante',
            name='prateleira',
        ),
        migrations.AddField(
            model_name='prateleira',
            name='estante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_api.Estante', verbose_name='prateleiras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='multas'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='multas'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
