# Generated by Django 3.0.1 on 2019-12-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0013_auto_20191227_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade_pagina',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='sinopse',
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_lancamento',
            field=models.CharField(max_length=4),
        ),
    ]
