# Generated by Django 3.0.1 on 2019-12-28 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca_api', '0014_auto_20191228_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_emprestimos', to='Biblioteca_api.Livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emprestimo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estante',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes_genero', to='Biblioteca_api.Genero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='Biblioteca_api.Genero'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_multas', to='Biblioteca_api.Livro'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_multas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prateleira',
            name='estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prateleiras', to='Biblioteca_api.Estante'),
        ),
    ]
