# Generated by Django 3.0.1 on 2019-12-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0015_auto_20191228_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prateleira',
            name='ordenacao_letra',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='quantidade_atual',
        ),
        migrations.RemoveField(
            model_name='prateleira',
            name='quantidade_suportada',
        ),
    ]
