# Generated by Django 3.0.1 on 2019-12-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0016_auto_20191231_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade',
        ),
    ]
