# Generated by Django 3.0.1 on 2020-01-07 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca_api', '0018_delete_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('pagar', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_multa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
