# Generated by Django 3.0.1 on 2020-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0022_auto_20200108_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='estante',
            name='espaco_sobrando',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
