# Generated by Django 3.0.1 on 2020-01-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0023_estante_espaco_sobrando'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='data_pagar',
            field=models.DateField(default='2019-02-02'),
            preserve_default=False,
        ),
    ]
