# Generated by Django 3.0.1 on 2020-01-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_api', '0024_multa_data_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='data_pagar',
            field=models.DateField(null=True),
        ),
    ]
